version: '3.1'
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis

  # Database Postgres
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: postgres_db

  # Django Application
  app:
    build: .
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    depends_on:
      - db

  # Celery
  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    env_file:
      - ./.env

    container_name: celery-beat
    depends_on:
      - db
      - redis
      - app

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    env_file:
      - ./.env

    container_name: celery
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data: