# Generated by Django 4.1 on 2022-08-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
